### ISSUE TITLE
[Roadmap] vanilla-calendar-pro v3.0.0

### ISSUE THREAD

**Issue by uvarov-frontend** [uvarov-frontend/vanilla-calendar-pro#293]
This issue contains a roadmap for the development of a new version of vanilla-calendar-pro v3.0.0. The purpose of this version is to add new features, improve performance, and fix known bugs.

- [x] Completely get rid of the dependence of css classes in the code, add full support for Tailwind. #247 #260
- [x] Add the ability to set custom weekends for each week. Use an array to define the week. For example: `weekends: [5,6]` #286 #291
- [x] Add customizable week start day. #308 
- [x] Add the ability to install custom themes created manually. Create a new custom theme.
- [x] Add feature prevent month change when selecting days from another month. #306 
- [x] Remove re-render after click in current month. Fix event displaying pop-ups in mobile versions. #287 
- [x] Fix calendar grid styles.
- [x] Make the day of the week clickable like the week number.
- [x] Maximize accessibility, add `aria` labels, tabindex, etc. to the layout. Implement full calendar control from the keyboard. #233
- [x] Add full support for control using keyboard arrows or joystick. 🤩
- [x] Fix date rounding in date range selection mode. #313 
- [x] Add maximum and minimum installation time to Time Picker. #234
- [x] ~~Add the ability to select a time range. #232~~
- [x] Refactoring the calendar settings API. #314 
- [x] Perform type refactoring #279 
- [x] Add `setSettings(...options)` method instead of overriding `calendar.settings = { ...newOptions }` #273 

For now, this is all that is planned to be implemented in the new version. In addition to the above, it is planned to carry out partial refactoring to optimize the code.

Write your suggestions for the new version in this Issue, thanks for your input and support, whatever it may be. 🙂

**Comment by ghiscoding** [comment]
For the weekends, if we look at the air-datepicker project, we can change both the weekends and the first day that the calendar begins. 

![image](https://github.com/user-attachments/assets/e7a174d7-0640-45bd-8e70-aad02cf8e8df)

**Comment by johanrd** [comment]
Nice list! Especially `independence of css classes` and `weekend settings` will be powerful!

**Comment by uvarov-frontend** [comment]
Implemented custom weekends #291 and any custom first day of the week. #308

**Comment by ghiscoding** [comment]
Another thing that might be nice to fix is that in Angular, I'm receiving these 2 warnings

![image](https://github.com/user-attachments/assets/b8f45c2a-fd9d-4eae-bf26-7429814e0289)

the problems is that these 2 files are created by hand and are also included in the GitHub project, it's also why we have to import types differently `import type { IOptions } from 'vanilla-calendar-pro/types';`. We did discuss this a bit in #279 which you pointed me to the different import for types and the possible breaking change to move types in the default export, it might be a good time to refactor these and fix the warnings. But taking a look at some articles on the internet (like this [article](https://medium.com/@shlomisderot/how-to-get-rid-the-warning-xxx-ts-is-part-of-the-typescript-compilation-but-its-unused-5ea9ec85f3ec)), it might be fixable by simply modifying your `tsconfig.json` and add this (you might need to adjust the path of these files)
```ts
{
 "compilerOptions": { ... },
  "files": [
    "./classes.ts",
    "./types.ts"
  ]
}
```

**Comment by uvarov-frontend** [comment]
@ghiscoding Добавил в дорожную карту, спасибо

**Comment by uvarov-frontend** [comment]
I've implemented all the new features and fixed all the bugs I'm aware of so far. All I need to do is refactor the calendar settings API and its types for the new version, and add a `changeSetting` method for the new API.

@ghiscoding Do you have any recommendations for me on how to design a new API and types for the calendar?

**Comment by ghiscoding** [comment]
ah great then I'm all for it. Thanks 😃

**Comment by ghiscoding** [comment]
Also I guess that renaming all settings to camelCase should be enough, though feel free to rename as you wish (i.e. `settings.selected.dates` => `selectedDates`). You could also compare your settings with the [air-datepicker](https://air-datepicker.com/docs) project, they also use flat options and some of the previous PRs I've made were based on some of their options, so having similar option names is not a bad thing for easy migration between the 2 projects, which is hopefully external users migrating to your project ;) 

I was also wondering does the Tailwind change you recently made, was that going to impact the build size? I don't personally use Tailwind at all and I'm fine with your current light/dark theme, so making it easier to use with Tailwind is nice but I hope it doesn't impact the final CSS build size. Loving your project and all these 3.0 upcoming changes sounds really great 🚀

**Comment by uvarov-frontend** [comment]
> Also I guess that renaming all settings to camelCase should be enough, though feel free to rename as you wish (i.e. `settings.selected.dates` => `selectedDates`). You could also compare your settings with the [air-datepicker](https://air-datepicker.com/docs) project, they also use flat options and some of the previous PRs I've made were based on some of their options, so having similar option names is not a bad thing for easy migration between the 2 projects, which is hopefully external users migrating to your project ;)
> 
> I was also wondering does the Tailwind changes you recently made on the customizations of CSS classes, will that going to impact the build size? I don't personally use Tailwind at all and I'm fine with your current light/dark theme, so making it easier to use with Tailwind is nice but I hope it doesn't impact the final CSS build size too much. Loving your project and all of these 3.0 upcoming changes which is going to boost the usability even more, great work. 🚀
> 
> hey maybe a final suggestion on a user level, you should add some kind of sponsors (donations) on your page, it could be [GitHub Sponsors](https://github.com/sponsors), [Ko-Fi](https://ko-fi.com/Account/Login) or others depending on availability in your area, I like Ko-Fi, it's free and easy to setup and it's also available on your side, a coffee isn't much but it's always nice to receive ;) Cheers

Don't worry about Tailwind, I end up creating calendar styling classes the same way as before. And at the output we have the same css files for styling as before, as far as I remember their weight is even less than it was.

The differences are that previously it was possible to specify only one class in `CSSClasses` for each of the keys, like this: `calendar: 'vanilla-calendar'`, this was necessary since there was a dependence on the specified class when searching for a selector in the code. Now there is no such problem and binding occurs using data attributes. Now you can specify a list of classes from Tailwind in the same key and everything will work without problems: `calendar: 'relative box-border min-w-[272px] flex flex-col p-4 rounded-xl opacity-100 transition-opacity' `.

This is how I solved the problem for those who want to use multiple classes from Tailwind, I added support for Tailwind, but this does not mean that I made it by default in the project.

I also generated a new color scheme using ChatGPT for some variety. This is what she looks like:
![Screen-Shot-2024-10-30-08-45-54](https://github.com/user-attachments/assets/70d09f7a-d935-45eb-9ae6-45a6507e709c)

It's called `slate-light`, in order to use it you just need to specify it as a theme: `theme: 'slate-light'`, by default the themes are the same as before: `'light'` and `'dark '`.
In the future we may create a directory of custom themes, anyone can create a new theme.

**Comment by uvarov-frontend** [comment]
I created a new API map for all calendar options and actions #316

**Comment by ghiscoding** [comment]
ah that's great if the CSS size is the same (or even smaller awesome), personally I just use SASS and provide variables to external users if they want to customize the colors and such. It could be nice to have SASS variables to customize a bit more, but I'm also fine without them since we can add our own classes anyway. I quite like the current project colors but I'm not color blind, so maybe ChatGPT gave you these colors because they are better for these users!?

> I created a new API map for all calendar options and actions #316

oh nice, looking great, flat options are coming 🚀

**Comment by uvarov-frontend** [comment]
> I quite like the current project colors but I'm not color blind, so maybe ChatGPT gave you these colors because they are better for these users!?

It's unlikely. My request was not related to color blindness)

**Comment by uvarov-frontend** [comment]
> Another thing that might be nice to fix is that in Angular, I'm receiving these 2 warnings
> 
> ![image](https://private-user-images.githubusercontent.com/643976/379909507-b8f45c2a-fd9d-4eae-bf26-7429814e0289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Nzg4MTgsIm5iZiI6MTczMDQ3ODUxOCwicGF0aCI6Ii82NDM5NzYvMzc5OTA5NTA3LWI4ZjQ1YzJhLWZkOWQtNGVhZS1iZjI2LTc0Mjk4MTRlMDI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGVkMjM1YmMxZTNiZWM4N2ZmZDk1YzZlZDBmZGRjY2Q3OTM3MjcxY2QxMDgwYzZjZTM1MGNiZTNkOWVkZDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8IVqu-JNsxStVEWvLBWIhirhdPzqFzNtDx_Leg4SaL4)
> 
> the problems is that these 2 files are created by hand and are also included in the GitHub project, it's also why we have to import types differently `import type { IOptions } from 'vanilla-calendar-pro/types';`. We did discuss this a bit in #279 which you pointed me to the different import for types and the possible breaking change to move types in the default export, it might be a good time to refactor these and fix the warnings. But taking a look at some articles on the internet (like this [article](https://medium.com/@shlomisderot/how-to-get-rid-the-warning-xxx-ts-is-part-of-the-typescript-compilation-but-its-unused-5ea9ec85f3ec)), it might be fixable by simply modifying your `tsconfig.json` and add this (you might need to adjust the path of these files)
> 
> ```ts
> {
>  "compilerOptions": { ... },
>   "files": [
>     "./classes.ts",
>     "./types.ts"
>   ]
> }
> ```

@ghiscoding Please check if there are warnings and errors that you mentioned in [3.0.0-beta.3](https://www.npmjs.com/package/vanilla-calendar-pro/v/3.0.0-beta.3) when importing a calendar in Angular. I was unable to reproduce the problem.

**Comment by ghiscoding** [comment]
great thanks, I'll give a try to your beta probably next week. Even quickly looking at the end result on [unpkg](https://unpkg.com/browse/vanilla-calendar-pro@3.0.0-beta.2/), I don't see these 2 files in the root of the package and so it should be all fine (the error from Angular was because the files where in the root without being referenced in any `index.ts` or `d.ts` and that is no longer the case so the error should all be gone). Thanks a lot for all this huge 3.0 refactoring, I will provide feedback next week. Cheers

**Comment by uvarov-frontend** [comment]
I have everything ready for the release of version 3.0.0, expect it soon.
